spring.application.name=Application

#DataBase Configuration
spring.datasource.name= eduguide
spring.datasource.url= jdbc:mysql://localhost:3306/eduguide
spring.datasource.username=root
spring.datasource.password=db2024
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Java Mail Sender Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eduguidechatbot@gmail.com
spring.mail.password=ampafcbnikfntdrq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#Google Sign in Configuration
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id= 599965805060-2lmq0p6vfk1o5dnviqo20s0op8d8khle.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret= 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

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
